# Generated by Django 3.1 on 2021-08-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugat',
            name='ingilizcha',
        ),
        migrations.RemoveField(
            model_name='lugat',
            name='uzbekcha',
        ),
        migrations.AddField(
            model_name='lugat',
            name='english',
            field=models.CharField(default=1, max_length=200, verbose_name='Inglizcha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugat',
            name='uzbek',
            field=models.CharField(default=1, max_length=200, verbose_name='O`zbekcha'),
            preserve_default=False,
        ),
    ]
