# Generated by Django 3.2.6 on 2021-08-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0002_auto_20210823_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugat',
            old_name='english',
            new_name='ingilizcha',
        ),
        migrations.RenameField(
            model_name='lugat',
            old_name='uzbek',
            new_name='uzbekcha',
        ),
    ]
